# Generated by Django 4.2.23 on 2025-08-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_field', models.CharField(blank=True, max_length=255, null=True)),
                ('current_level', models.CharField(blank=True, max_length=50, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('linked_in_profile', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
