# Generated by Django 5.2.5 on 2025-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
