# Generated by Django 5.2.5 on 2025-09-10 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_menteeprofile_interests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='favorite_mentors',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='profiles.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['average_rating'], name='profiles_me_average_c84add_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['is_featured'], name='profiles_me_is_feat_c456aa_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['is_new'], name='profiles_me_is_new_8ae4af_idx'),
        ),
        migrations.AddField(
            model_name='mentorreview',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='profiles.menteeprofile'),
        ),
        migrations.AddField(
            model_name='mentorreview',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='profiles.menteeprofile'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to='profiles.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorreview',
            name='mentorship_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='profiles.mentorshiprequest'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['status'], name='profiles_me_status_237983_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['created_at'], name='profiles_me_created_c461c7_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorreview',
            index=models.Index(fields=['rating'], name='profiles_me_rating_a97951_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorreview',
            index=models.Index(fields=['created_at'], name='profiles_me_created_82cef1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorreview',
            unique_together={('mentee', 'mentorship_request')},
        ),
    ]
