# Generated by Django 5.2.5 on 2025-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_mentorreview_mentorshiprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
