# Generated by Django 5.2.5 on 2025-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
